#!/usr/bin/env python3
"""fw/tools/gen.py: write fw/gen/*.h from the design sources (FWSIM-R5, FWSIM-R6, FWSIM-R64). Never edit fw/gen by hand.

  board_config.h    pins, AF numbers, ADC channels of U1 from docs/system/pin-contract.yaml + the circuit (hw/current.yaml design,
                    via tools/checks/interfaces.py) + ST open pin data. REFUSES to write if the interfaces [pins] check FAILs.
  variant_config.h  per-cell and per-exemption constants from fw/variants.yaml (incl. the FWSIM-R64 output current clamp)
  knobs_def.h       fw_knobs_t X-macro + hard clamps from fw/spec/knobs.yaml
  tables.h          float32 hex-literal tables (dB -> amplitude), so core never calls powf (determinism rules)
  dsp_tables.h      DSP filters + tables (window, mic EQ, noise calibration, sine, FFT, interpolator, half-band, algorithm A, NTF)

  python3 fw/tools/gen.py           regenerate
  python3 fw/tools/gen.py --check   regenerate into memory, exit 1 if any committed fw/gen file differs (fwsim stage gen)
Run with the tool venv (`source tools/env.sh`): the pins check builds the SKiDL circuit and needs pcbnew/skidl.
"""
import argparse
import contextlib
import hashlib
import io
import json
import math
import os
import struct
import sys
import tempfile
from pathlib import Path

import yaml

FW = Path(__file__).resolve().parents[1]
REPO = FW.parent
GEN = FW / "gen"
HDR = "/* GENERATED by fw/tools/gen.py from {src}. DO NOT EDIT: change the source and rerun `python3 fw/tools/gen.py`.\n * inputs sha256: {h} */\n"


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()[:16]


def inputs_hash(paths):
    """paths: files, or (name, bytes) pairs for derived inputs (e.g. only the active block of hw/current.yaml)."""
    h = hashlib.sha256()
    for p in paths:
        if isinstance(p, tuple):
            h.update(p[0].encode())
            h.update(p[1])
            continue
        h.update(str(Path(p).relative_to(REPO)).encode())
        h.update(Path(p).read_bytes())
    return h.hexdigest()[:16]


def active_design_bytes():
    """The ACTIVE design block of hw/current.yaml only (tools/current.py selection, ULTRASONIC_DESIGN respected), canonical JSON without
    the bookkeeping keys, so adding or editing a non-selected variant or the reference block does not stale the firmware."""
    sys.path.insert(0, str(REPO / "tools"))
    import current as C                                             # noqa: E402
    top, ref, variants = C._load(REPO / "hw/current.yaml")
    want = (os.environ.get(C.ENV) or "").strip().lower()
    blocks = [top, ref, *variants.values()]
    block = top if want in ("", "current", str(top.get("id", "")).lower()) else \
        (ref if want in ("reference", "revf", str(ref.get("id", "")).lower()) else next(b for b in blocks if str(b.get("id", "")).lower() == want))
    keep = {k: v for k, v in block.items() if not isinstance(v, dict) and k not in ("updated", "schema")}
    return ("hw/current.yaml[active]", json.dumps(keep, sort_keys=True, default=str).encode())


def cstr(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def hexf(x):
    """float32 value as a C hex float literal (exact)."""
    f = struct.unpack("<f", struct.pack("<f", x))[0]
    if f == 0.0:
        return "0x0p+0f"
    return float.hex(f) + "f"


# ------------------------------------------------------------------------------------------- board_config.h
def board_config():
    sys.path.insert(0, str(REPO / "tools/checks"))
    import interfaces as I                                          # noqa: E402  (applies hw/current.yaml: POD_PACKAGES)
    contract = I.load_yaml(I.CFG.contract)
    with contextlib.redirect_stdout(io.StringIO()), tempfile.TemporaryDirectory(dir=os.environ.get("TMPDIR")) as tmp:
        cwd = os.getcwd()
        os.chdir(tmp)
        try:
            sch = I.read_schematic()
        finally:
            os.chdir(cwd)
    data = I.read_pin_data(contract)
    res = I.check_pins(contract, sch, data)
    if res.status == I.FAIL:
        raise SystemExit(f"gen: interfaces [pins] FAIL, board_config.h NOT written: {res.msg}\n  " + "\n  ".join(res.details[:10]))
    ref = contract["mcu"]["ref"]
    nets = {num: net for num, (_, net) in sch.parts[ref]["pins"].items()}
    rows = []
    for e in contract["signals"]:
        net, why, _ = I.resolve_net(e, sch)
        if net is None:
            raise SystemExit(f"gen: {e['id']}: {why}")
        pos = [n for n, x in nets.items() if x == net]
        pin = data.pins[int(pos[0])]
        got = I.provides(e["signal"], pin)
        port = pin["port"]
        p_letter, p_num = (port[1], int(port[2:])) if port.startswith("P") and port[2:].isdigit() else ("\\0", 0)
        sig = got[0]
        adc = None
        if e["signal"].startswith("re:ADC"):
            pref = [s for s in got if s.startswith("ADC1_")] or got          # ADC1 unless only ADC4 provides it (VBAT_SENSE)
            sig = pref[0]
            adc = (int(sig[3]), int(sig.split("_IN")[1]))
        af_st = sorted(data.af.get(port, {}).get(sig, set()))
        af = e.get("af")
        if af is not None and af not in af_st:
            raise SystemExit(f"gen: {e['id']}: contract AF{af} not in ST's table {af_st} for {port} {sig}")
        rows.append(dict(id=e["id"], net=net, port=p_letter, num=p_num, pkg=int(pos[0]), af=af if af is not None else 255, sig=sig, adc=adc,
                         alts=got, hazard=any(h["port"] == port for h in contract.get("hazards", []))))
    srcs = [I.CFG.contract, REPO / contract["mcu"]["mcu_xml"], REPO / contract["mcu"]["gpio_xml"], I.CFG.netlist, active_design_bytes()]
    design = getattr(I.DESIGN, "id", "?")
    out = [HDR.format(src="docs/system/pin-contract.yaml + circuit of hw/current.yaml (active design block) + ST open pin data", h=inputs_hash(srcs)),
           f"/* design {design}; interfaces [pins] {res.status}: {res.msg[:160]} */",
           "#ifndef FW_GEN_BOARD_CONFIG_H\n#define FW_GEN_BOARD_CONFIG_H\n#include <stdint.h>\n",
           f"#define BOARD_DESIGN_ID {cstr(design)}",
           f"#define BOARD_MCU {cstr(contract['mcu']['part'].split()[0])}",
           f"#define BOARD_PACKAGE {cstr(contract['mcu']['package'])}",
           "#define BOARD_AF_NONE 255u\n",
           "typedef enum {"]
    out += [f"    BOARD_PIN_{r['id']}," for r in rows]
    out += ["    BOARD_PIN_COUNT\n} board_pin_t;\n",
            "typedef struct {\n    char port;            /* 'A'..'H'; '\\0' for NRST */\n    uint8_t num;          /* port bit */\n"
            "    uint8_t pkg_pin;      /* UFQFPN48 position */\n    uint8_t af;           /* GPIO_AFn, BOARD_AF_NONE for GPIO/analog/system */\n"
            "    uint8_t hazard;       /* pin-contract.yaml hazards row on this port (ECR-0013) */\n    const char *net;\n    const char *signal;\n} board_pin_info_t;\n",
            "#define BOARD_PIN_TABLE_INIT { \\"]
    out += [f"    {{'{r['port']}', {r['num']}u, {r['pkg']}u, {r['af']}u, {int(r['hazard'])}u, {cstr(r['net'])}, {cstr(r['sig'])}}}, /* {r['id']}{' alt: ' + ','.join(r['alts']) if len(r['alts']) > 1 else ''} */ \\" for r in rows]
    out += ["}\n"]
    for r in rows:
        out.append(f"#define BOARD_{r['id']}_PORT '{r['port']}'\n#define BOARD_{r['id']}_PIN {r['num']}u\n#define BOARD_{r['id']}_AF {r['af']}u")
        if r["adc"]:
            out.append(f"#define BOARD_{r['id']}_ADC {r['adc'][0]}u\n#define BOARD_{r['id']}_ADC_CH {r['adc'][1]}u")
    out.append("\n#endif\n")
    return "\n".join(out), [s[0] if isinstance(s, tuple) else str(Path(s).relative_to(REPO)) for s in srcs]


# ------------------------------------------------------------------------------------------- variant_config.h
def variant_config():
    v = yaml.safe_load((FW / "variants.yaml").read_text())
    b = {k: x["val"] for k, x in v["bridge"].items()}
    out = [HDR.format(src="fw/variants.yaml", h=inputs_hash([FW / "variants.yaml"])),
           "#ifndef FW_GEN_VARIANT_CONFIG_H\n#define FW_GEN_VARIANT_CONFIG_H\n"]
    ids = list(v["cells"])
    for i, cid in enumerate(ids):
        out.append(f"#define FW_CELL_{cid} {i + 1}")
    out.append(f"#ifndef FW_CELL\n#define FW_CELL FW_CELL_{v['default_cell']}\n#endif\n")
    out.append("#define FW_EXEMPTION_a 1\n#define FW_EXEMPTION_b 2")
    out.append(f"#ifndef FW_SELFTEST_EXEMPTION\n#define FW_SELFTEST_EXEMPTION FW_EXEMPTION_{v['selftest_exemption']['default']}\n#endif\n")
    out.append(f"/* bridge (FWSIM-R64): vdd {b['vdd_v']} V, r_exciter {b['r_exciter_ohm']} ohm + r_path {b['r_path_ohm']} ohm; U4 {b['u4_rating_ma']} mA x {b['u4_derate']} */")
    out.append(f"#define FW_VAR_VDD_MV {round(b['vdd_v'] * 1000)}\n#define FW_VAR_R_LOAD_MOHM {round((b['r_exciter_ohm'] + b['r_path_ohm']) * 1000)}\n")
    first = True
    for cid, c in v["cells"].items():
        i_max = math.floor(min(b["cell_derate"] * c["pulse_ma"], b["u4_derate"] * b["u4_rating_ma"]))
        amp = i_max * 1e-3 * (b["r_exciter_ohm"] + b["r_path_ohm"]) / b["vdd_v"]
        ppm = min(1000000, math.floor(amp * 1e6))
        out.append(f"{'#if' if first else '#elif'} FW_CELL == FW_CELL_{cid}   /* {c['gloss']}; {c['src']} */")
        out.append(f"#define FW_VAR_CELL_NAME {cstr(cid)}\n#define FW_VAR_CELL_MAH {c['capacity_mah']}\n#define FW_VAR_CELL_PULSE_MA {c['pulse_ma']}")
        out.append(f"#define FW_VAR_I_PEAK_MA_MAX {i_max}   /* min({b['cell_derate']} x {c['pulse_ma']}, {b['u4_derate']} x {b['u4_rating_ma']}) mA */")
        out.append(f"#define FW_VAR_AMP_MAX_PPM {ppm}u   /* |V_diff/Vdd| at that current = {amp:.4f} ({20 * math.log10(amp):.2f} dBFS) */")
        out.append(f"#define FW_VAR_ICHG_CODE_MAX {c['ichg_code_max']}\n#define FW_VAR_VBATREG_CODE_MAX {c['vbatreg_code_max']}")
        first = False
    out.append("#else\n#error \"FW_CELL: unknown cell (fw/variants.yaml cells)\"\n#endif\n")
    out.append("#if FW_SELFTEST_EXEMPTION == FW_EXEMPTION_a\n#define FW_VAR_DOCKED_OUTPUT_MAX 1\n#define FW_VAR_EXEMPTION_NAME \"a\"\n"
               "#elif FW_SELFTEST_EXEMPTION == FW_EXEMPTION_b\n#define FW_VAR_DOCKED_OUTPUT_MAX 0\n#define FW_VAR_EXEMPTION_NAME \"b\"\n"
               "#else\n#error \"FW_SELFTEST_EXEMPTION: a or b (ECR-0009)\"\n#endif\n")
    out.append("#endif\n")
    return "\n".join(out), ["fw/variants.yaml"]


# ------------------------------------------------------------------------------------------- knobs_def.h
def knobs_def():
    k = yaml.safe_load((FW / "spec/knobs.yaml").read_text())
    out = [HDR.format(src="fw/spec/knobs.yaml", h=inputs_hash([FW / "spec/knobs.yaml"])),
           "#ifndef FW_GEN_KNOBS_DEF_H\n#define FW_GEN_KNOBS_DEF_H\n#include \"variant_config.h\"\n",
           f"#define FW_KNOBS_VERSION {int(k['version'])}u"]
    ids = [x["id"] for x in k["knobs"]]
    if len(set(ids)) != len(ids):
        raise SystemExit("gen: duplicate knob id")
    layout = int(hashlib.sha256(("|".join(ids)).encode()).hexdigest()[:8], 16)
    out.append(f"#define FW_KNOBS_LAYOUT_HASH 0x{layout:08x}u   /* sha256 of the ordered id list: a reorder or rename changes it; fwlint:data */\n")
    out.append("/* hard clamps: no knob may pass these (static asserts in fw/core/knobs.c) */")
    for name, hc in k["hard_clamps"].items():
        out.append(f"#define {name} ({hc['val']})   /* {hc['src']} */")
    hc_ceiling = k["hard_clamps"]["HC_CEILING_CDB_MAX"]["val"]
    peak_ppm = math.ceil(10.0 ** (hc_ceiling / 2000.0) * 1e6)
    shaper_ppm = math.ceil(7.67 * 1.5 / 100.0 * 1e6)
    out.append(f"\n#define HC_CEILING_PEAK_PPM {peak_ppm}u   /* 10^(HC_CEILING_CDB_MAX/2000), rounded up */")
    out.append(f"#define FW_SHAPER_EXCURSION_PPM {shaper_ppm}u   /* sum|ntf| x 1.5 LSB / (ARR/2) = 7.67 x 1.5 / 100 at ARR 200 (FWSIM-R15 bound b) */")
    out.append("\n/* X(id, def, min, max, unit, src) */\n#define FW_KNOBS(X) \\")
    for x in k["knobs"]:
        src = k["assumed"] if x["src"] == "assumed" else x["src"]
        out.append(f"    X({x['id']}, ({x['def']}), ({x['min']}), ({x['max']}), {cstr(x['unit'])}, {cstr(src)}) \\")
    out.append("\n/* H(id, bound, HC): bound 'max' => the knob's max <= HC; 'min' => min >= HC */\n#define FW_KNOBS_HARD(H) \\")
    for x in k["knobs"]:
        for bound, hc in (x.get("hard") or {}).items():
            out.append(f"    H({x['id']}, {bound}, {hc}) \\")
    out.append("\n/* E(id, value): knobs restricted to a value set */\n#define FW_KNOBS_ENUM(E) \\")
    for x in k["knobs"]:
        for val in x.get("enum") or []:
            out.append(f"    E({x['id']}, {val}) \\")
    out.append("\n#endif\n")
    return "\n".join(out), ["fw/spec/knobs.yaml"]


# ------------------------------------------------------------------------------------------- tables.h
DB_MIN_CDB, DB_STEP_CDB = -8000, 10


def tables():
    n = -DB_MIN_CDB // DB_STEP_CDB + 1
    vals = [10.0 ** ((DB_MIN_CDB + i * DB_STEP_CDB) / 2000.0) for i in range(n)]
    out = [HDR.format(src="fw/tools/gen.py tables()", h=hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:16]),
           "#ifndef FW_GEN_TABLES_H\n#define FW_GEN_TABLES_H\n",
           f"#define FW_DB_TABLE_MIN_CDB ({DB_MIN_CDB})\n#define FW_DB_TABLE_STEP_CDB {DB_STEP_CDB}\n#define FW_DB_TABLE_N {n}u\n",
           "/* 10^(cdB/2000) for cdB = MIN + i*STEP, float32 exact hex */",
           "#define FW_DB_TABLE_INIT { \\"]
    for i in range(0, n, 6):
        out.append("    " + ", ".join(hexf(v) for v in vals[i:i + 6]) + ", \\")
    out.append("}\n\n#endif\n")
    return "\n".join(out), ["fw/tools/gen.py"]


# ------------------------------------------------------------------------------------------- dsp_tables.h
def dsp_tables():
    sys.path.insert(0, str(FW / "tools"))
    import dsp_tables as dt                                          # noqa: E402
    srcs = [FW / "tools/dsp_tables.py", REPO / "sim/dsp/pipeline.py", REPO / "sim/data/sph0641_ultrasonic_response.json"]
    hdr = HDR.format(src="fw/tools/dsp_tables.py (filters + tables from sim/dsp/pipeline.py, sim/e2e/stages.py)", h=inputs_hash(srcs))
    return dt.generate(hdr), [str(Path(s).relative_to(REPO)) for s in srcs]


# ------------------------------------------------------------------------------------------- fsm_table.h
def fsm_table():
    f = yaml.safe_load((FW / "spec/fsm.yaml").read_text())
    st, ev, ac, gd = f["states"], f["events"], f["actions"], f["guards"]
    special = ["SAME", "PREV", "PREV_TOGGLED", "DEFAULT"]
    cells = {}
    for s_ in st:
        row = f["transitions"].get(s_)
        if row is None:
            raise SystemExit(f"gen: fsm state {s_} has no row")
        seen = []
        for e, t in row.items():
            if e == "ignore":
                for x in t:
                    cells[(s_, x)] = None
                    seen.append(x)
                continue
            tgt, act, grd = t[0], (t[1] if len(t) > 1 else "NONE"), (t[2] if len(t) > 2 else "ALWAYS")
            if tgt not in st + special or act not in ac or grd not in gd or e not in ev:
                raise SystemExit(f"gen: fsm {s_}.{e}: bad cell {t}")
            cells[(s_, e)] = (tgt, act, grd)
            seen.append(e)
        if sorted(seen) != sorted(ev) or len(seen) != len(set(seen)):
            raise SystemExit(f"gen: fsm state {s_}: every event exactly once (missing {sorted(set(ev) - set(seen))}, dup {sorted(x for x in seen if seen.count(x) > 1)})")
    out = [HDR.format(src="fw/spec/fsm.yaml", h=inputs_hash([FW / "spec/fsm.yaml"])), "#ifndef FW_GEN_FSM_TABLE_H\n#define FW_GEN_FSM_TABLE_H\n#include <stdint.h>\n"]
    out.append("typedef enum { " + ", ".join(f"FW_ST_{x}" for x in st) + ", FW_ST_COUNT } fw_mode_t;")
    out.append("typedef enum { " + ", ".join(f"FW_FE_{x}" for x in ev) + ", FW_FE_COUNT } fw_fsm_ev_t;")
    out.append("typedef enum { " + ", ".join(f"FW_AC_{x}" for x in ac) + " } fw_fsm_act_t;")
    out.append("typedef enum { " + ", ".join(f"FW_GD_{x}" for x in gd) + " } fw_fsm_guard_t;")
    out.append("typedef enum { FW_TG_STATE = 0, " + ", ".join(f"FW_TG_{x}" for x in special) + " } fw_fsm_tgkind_t;")
    out.append("typedef struct { uint8_t valid, kind, state, action, guard; } fw_fsm_cell_t;   /* valid 0 = explicit ignore */")
    out.append(f"#define FW_FSM_STATE_NAMES {{ {', '.join(chr(34) + x + chr(34) for x in st)} }}")
    out.append(f"#define FW_FSM_EVENT_NAMES {{ {', '.join(chr(34) + x + chr(34) for x in ev)} }}")
    out.append("#define FW_FSM_TABLE_INIT { \\")
    for s_ in st:
        row = []
        for e in ev:
            c = cells[(s_, e)]
            if c is None:
                row.append("{0, 0, 0, 0, 0}")
            else:
                tgt, act, grd = c
                kind = f"FW_TG_{tgt}" if tgt in special else "FW_TG_STATE"
                stv = f"FW_ST_{tgt}" if tgt in st else "0"
                row.append(f"{{1, {kind}, {stv}, FW_AC_{act}, FW_GD_{grd}}}")
        out.append(f"    /* {s_} */ {{ " + ", ".join(row) + " }, \\")
    out.append("}")
    g = f["gestures"]
    raw = g["raw"]
    out.append("typedef enum { " + ", ".join(f"FW_RG_{x}" for x in raw) + ", FW_RG_COUNT } fw_raw_gesture_t;")
    out.append("typedef struct { int8_t ev[FW_RG_COUNT]; uint8_t hold1_repeats, double_used; } fw_gesture_map_t;   /* ev -1 = unused */")
    out.append("#define FW_GESTURE_MAPS_INIT { \\")
    for opt in ("A", "B", "C"):
        m = g[opt]
        evs = ", ".join("-1" if m[r] == "NONE" else f"FW_FE_{m[r]}" for r in raw)
        out.append(f"    /* {opt} */ {{{{{evs}}}, {int(m['hold1_repeats'])}u, {int(m['double'])}u}}, \\")
    out.append("}\n#endif\n")
    return "\n".join(out), ["fw/spec/fsm.yaml"]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if a committed fw/gen file differs from a fresh generation")
    ap.add_argument("--json", type=Path, help="write a result row here")
    a = ap.parse_args(argv)
    outputs = {"board_config.h": board_config, "variant_config.h": variant_config, "knobs_def.h": knobs_def, "tables.h": tables, "dsp_tables.h": dsp_tables, "fsm_table.h": fsm_table}
    stale, srcs = [], {}
    for name, fn in outputs.items():
        text, s = fn()
        srcs[name] = s
        path = GEN / name
        if a.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            GEN.mkdir(exist_ok=True)
            path.write_text(text)
    row = {"stale": stale, "sources": srcs, "hashes": {n: sha(GEN / n) for n in outputs if (GEN / n).exists()}}
    if a.json:
        a.json.write_text(json.dumps(row, indent=2) + "\n")
    if stale:
        print(f"gen: STALE {stale}: run `python3 fw/tools/gen.py` and commit fw/gen", file=sys.stderr)
        return 1
    print("gen: " + ("fw/gen up to date" if a.check else f"wrote {', '.join(outputs)}"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
